-- create tables

create table tms_departments (
    dept_id       number generated by default on null as identity
                  constraint tms_departments_dept_id_pk primary key,
    name          varchar2(100 char) not null,
    manager_id    number,
    location      varchar2(150 char),
    color         varchar2(30 char)
);



create table tms_jobs (
    job_id        number generated by default on null as identity
                  constraint tms_jobs_job_id_pk primary key,
    dept_id       number                  constraint tms_jobs_dept_id_fk
                  references tms_departments,
    title         varchar2(150 char) not null,
    min_salary    number,
    max_salary    number
);

-- table index
create index tms_jobs_i1 on tms_jobs (dept_id);



create table tms_job_requisitions (
    req_id          number generated by default on null as identity
                    constraint tms_job_requisitions_req_id_pk primary key,
    job_id          number                    constraint tms_job_requisitions_job_id_fk
                    references tms_jobs,
    dept_id         number                    constraint tms_job_requisitions_dept_id_fk
                    references tms_departments,
    requested_by    varchar2(255 char) not null,
    approved_by     varchar2(255 char),
    headcount       number,
    status          varchar2(30 char) constraint tms_job_requisitions_status_ck
                    check (status in ('Draft','Pending Approval','Open','Filled','Cancelled','Closed')),
    open_date       date,
    close_date      date
);

-- table index
create index tms_job_requisitions_i1 on tms_job_requisitions (job_id);

create index tms_job_requisitions_i2 on tms_job_requisitions (dept_id);



create table tms_candidates (
    candidate_id      number generated by default on null as identity
                      constraint tms_candidates_candidate_id_pk primary key,
    req_id            number                      constraint tms_candidates_req_id_fk
                      references tms_job_requisitions,
    first_name        varchar2(80 char) not null,
    last_name         varchar2(80 char) not null,
    email             varchar2(320 char) not null,
    phone             varchar2(50 char),
    resume_blob       blob,
    source            varchar2(100 char),
    current_stage     varchar2(30 char) constraint tms_candidates_current_stage_ck
                      check (current_stage in ('Applied','Screening','Interview','Offer','Hired','Rejected')),
    applied_date      date,
    diversity_flag    varchar2(1 char) constraint tms_candidates_diversity_flag_ck
                      check (diversity_flag in ('Y','N')),
    ai_score          number
);

-- table index
create index tms_candidates_i1 on tms_candidates (req_id);



create table tms_interview_stages (
    stage_id          number generated by default on null as identity
                      constraint tms_interview_stages_stage_id_pk primary key,
    candidate_id      number                      constraint tms_interview_stages_candidate_id_fk
                      references tms_candidates,
    req_id            number                      constraint tms_interview_stages_req_id_fk
                      references tms_job_requisitions,
    stage_name        varchar2(60 char) constraint tms_interview_stages_stage_name_ck
                      check (stage_name in ('Screening','Phone Screen','Technical Interview','Manager Interview','HR Interview','Offer Review','Final')),
    interviewer_id    number,
    scheduled_date    timestamp,
    outcome           varchar2(30 char) constraint tms_interview_stages_outcome_ck
                      check (outcome in ('Scheduled','Proceed','Hold','Rejected','No Show','Completed','Cancelled')),
    feedback_notes    clob,
    score             number
);

-- table index
create index tms_interview_stages_i1 on tms_interview_stages (candidate_id);

create index tms_interview_stages_i2 on tms_interview_stages (req_id);



create table tms_offers (
    offer_id             number generated by default on null as identity
                         constraint tms_offers_offer_id_pk primary key,
    candidate_id         number                         constraint tms_offers_candidate_id_fk
                         references tms_candidates,
    req_id               number                         constraint tms_offers_req_id_fk
                         references tms_job_requisitions,
    offered_salary       number,
    start_date           date,
    expiry_date          date,
    status               varchar2(30 char) constraint tms_offers_status_ck
                         check (status in ('Draft','Pending Approval','Sent','Accepted','Rejected','Expired','Withdrawn')),
    offer_letter_blob    blob,
    approved_by          varchar2(255 char)
);

-- table index
create index tms_offers_i1 on tms_offers (candidate_id);

create index tms_offers_i2 on tms_offers (req_id);



create table tms_employees (
    employee_id     number generated by default on null as identity
                    constraint tms_employees_employee_id_pk primary key,
    candidate_id    number                    constraint tms_employees_candidate_id_fk
                    references tms_candidates,
    job_id          number                    constraint tms_employees_job_id_fk
                    references tms_jobs,
    dept_id         number                    constraint tms_employees_dept_id_fk
                    references tms_departments,
    first_name      varchar2(80 char) not null,
    last_name       varchar2(80 char) not null,
    email           varchar2(320 char) not null,
    manager_id      number,
    salary          number,
    hire_date       date,
    status          varchar2(30 char) constraint tms_employees_status_ck
                    check (status in ('Onboarding','Active','Inactive','Terminated')),
    photo_blob      blob
);

-- table index
create index tms_employees_i1 on tms_employees (candidate_id);

create index tms_employees_i2 on tms_employees (job_id);

create index tms_employees_i3 on tms_employees (dept_id);



create table tms_onboarding_tasks (
    task_id           number generated by default on null as identity
                      constraint tms_onboarding_tasks_task_id_pk primary key,
    employee_id       number                      constraint tms_onboarding_tasks_employee_id_fk
                      references tms_employees,
    task_name         varchar2(200 char) not null,
    assigned_to       varchar2(255 char),
    category          varchar2(80 char),
    due_date          date,
    status varchar2(30 char)
  constraint tms_onboarding_tasks_status_ck
  check (
    status in (
      'Not Started',
      'In Progress',
      'Completed',
      'Blocked',
      'Cancelled',
      'Overdue'
    )
  ),
    completed_date    date
);

-- table index
create index tms_onboarding_tasks_i1 on tms_onboarding_tasks (employee_id);



create table tms_leave_types (
    leave_type_id        number generated by default on null as identity
                         constraint tms_leave_types_leave_type_id_pk primary key,
    name                 varchar2(100 char) not null,
    max_days_per_year    number
);



create table tms_leave_requests (
    request_id        number generated by default on null as identity
                      constraint tms_leave_requests_request_id_pk primary key,
    employee_id       number                      constraint tms_leave_requests_employee_id_fk
                      references tms_employees,
    leave_type_id     number                      constraint tms_leave_requests_leave_type_id_fk
                      references tms_leave_types,
    start_date        date,
    end_date          date,
    days_requested    number,
    reason            clob,
    status            varchar2(30 char) constraint tms_leave_requests_status_ck
                      check (status in ('Draft','Submitted','Approved','Rejected','Cancelled')),
    approver_id       number
);

-- table index
create index tms_leave_requests_i1 on tms_leave_requests (employee_id);

create index tms_leave_requests_i2 on tms_leave_requests (leave_type_id);



create table tms_leave_balances (
    balance_id       number generated by default on null as identity
                     constraint tms_leave_balances_balance_id_pk primary key,
    employee_id      number                     constraint tms_leave_balances_employee_id_fk
                     references tms_employees,
    leave_type_id    number                     constraint tms_leave_balances_leave_type_id_fk
                     references tms_leave_types,
    year             number,
    accrued          number,
    used             number,
    remaining        number
);

-- table index
create index tms_leave_balances_i1 on tms_leave_balances (employee_id);

create index tms_leave_balances_i2 on tms_leave_balances (leave_type_id);



create table tms_hr_policy (
    policy_id    number generated by default on null as identity
                 constraint tms_hr_policy_policy_id_pk primary key,
    category     varchar2(100 char) not null,
    title        varchar2(200 char) not null,
    content      clob
);



-- Generated by Quick SQL 1.2.9 7/17/2026, 12:44:31 PM

/*
tms_departments
  dept_id /pk
  name vc100 /nn
  manager_id num
  location vc150
  color vc30

tms_jobs
  job_id /pk
  title vc150 /nn
  min_salary num
  max_salary num
  dept_id /fk tms_departments

tms_job_requisitions
  req_id /pk
  job_id /fk tms_jobs
  dept_id /fk tms_departments
  requested_by vc255 /nn
  approved_by vc255
  headcount num
  status vc30 /check Draft, Pending Approval, Open, Filled, Cancelled, Closed
  open_date date
  close_date date

tms_candidates
  candidate_id /pk
  req_id /fk tms_job_requisitions
  first_name vc80 /nn
  last_name vc80 /nn
  email vc320 /nn
  phone vc50
  resume_blob blob
  source vc100
  current_stage vc30 /check Applied, Screening, Interview, Offer, Hired, Rejected
  applied_date date
  diversity_flag vc1 /check Y, N
  ai_score num

tms_interview_stages
  stage_id /pk
  candidate_id /fk tms_candidates
  req_id /fk tms_job_requisitions
  stage_name vc60 /check Screening, Phone Screen, Technical Interview, Manager Interview, HR Interview, Offer Review, Final
  interviewer_id num
  scheduled_date timestamp
  outcome vc30 /check Scheduled, Proceed, Hold, Rejected, No Show, Completed, Cancelled
  feedback_notes clob
  score num

tms_offers
  offer_id /pk
  candidate_id /fk tms_candidates
  req_id /fk tms_job_requisitions
  offered_salary num
  start_date date
  expiry_date date
  status vc30 /check Draft, Pending Approval, Sent, Accepted, Rejected, Expired, Withdrawn
  offer_letter_blob blob
  approved_by vc255

tms_employees
  employee_id /pk
  candidate_id /fk tms_candidates
  first_name vc80 /nn
  last_name vc80 /nn
  email vc320 /nn
  job_id /fk tms_jobs
  dept_id /fk tms_departments
  manager_id num
  salary num
  hire_date date
  status vc30 /check Onboarding, Active, Inactive, Terminated
  photo_blob blob

tms_onboarding_tasks
  task_id /pk
  employee_id /fk tms_employees
  task_name vc200 /nn
  assigned_to vc255
  category vc80
  due_date date
  status vc30 /check Not Started, In Progress, Completed, Blocked, Cancelled, Overdue
  completed_date date

tms_leave_types
  leave_type_id /pk
  name vc100 /nn
  max_days_per_year num

tms_leave_requests
  request_id /pk
  employee_id /fk tms_employees
  leave_type_id /fk tms_leave_types
  start_date date
  end_date date
  days_requested num
  reason clob
  status vc30 /check Draft, Submitted, Approved, Rejected, Cancelled
  approver_id num

tms_leave_balances
  balance_id /pk
  employee_id /fk tms_employees
  leave_type_id /fk tms_leave_types
  year num
  accrued num
  used num
  remaining num

tms_hr_policy
  policy_id /pk
  category vc100 /nn
  title vc200 /nn
  content clob

 Non-default options:
# settings = {"apex":"Y","db":"23","pk":"IDENTITY"}

*/