-- =========================================================
-- 1. TABLES
-- =========================================================

CREATE TABLE crm_roles (
    id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                     CONSTRAINT crm_roles_pk PRIMARY KEY,
    role_name        VARCHAR2(50)  NOT NULL UNIQUE,
    role_description VARCHAR2(500),
    row_version      INTEGER       NOT NULL,
    created_on       DATE          NOT NULL,
    created_by       VARCHAR2(255) NOT NULL,
    updated_on       DATE          NOT NULL,
    updated_by       VARCHAR2(255) NOT NULL
);


CREATE TABLE crm_users (
    id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
                   CONSTRAINT crm_users_pk PRIMARY KEY,
    username       VARCHAR2(50)  NOT NULL UNIQUE,
    email          VARCHAR2(100) NOT NULL UNIQUE,
    password_hash  VARCHAR2(255) NOT NULL,
    password_salt  VARCHAR2(64)  NOT NULL,
    password_plain VARCHAR2(255),
    first_name     VARCHAR2(50)  NOT NULL,
    last_name      VARCHAR2(50)  NOT NULL,

    role_id        NUMBER        NOT NULL
                   CONSTRAINT crm_users_role_fk
                   REFERENCES crm_roles(id) ON DELETE CASCADE,

    phone          VARCHAR2(20),
    row_version    INTEGER       NOT NULL,
    created_on     DATE          NOT NULL,
    created_by     VARCHAR2(255) NOT NULL,
    updated_on     DATE          NOT NULL,
    updated_by     VARCHAR2(255) NOT NULL
);


CREATE INDEX crm_users_indx_1
    ON crm_users(role_id);



-- =========================================================
-- 2. TRIGGERS
-- =========================================================

CREATE OR REPLACE TRIGGER crm_roles_biu
BEFORE INSERT OR UPDATE ON crm_roles
FOR EACH ROW
BEGIN
    :new.updated_on := SYSDATE;
    :new.updated_by := COALESCE(
                           SYS_CONTEXT('APEX$SESSION','APP_USER'),
                           USER
                       );

    IF INSERTING THEN
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    ELSE
        :new.row_version := NVL(:old.row_version, 0) + 1;
    END IF;
END;
/
    

CREATE OR REPLACE TRIGGER crm_users_biu
BEFORE INSERT OR UPDATE ON crm_users
FOR EACH ROW
BEGIN
    :new.updated_on := SYSDATE;
    :new.updated_by := COALESCE(
                           SYS_CONTEXT('APEX$SESSION','APP_USER'),
                           USER
                       );

    IF INSERTING THEN
        :new.row_version := 1;
        :new.created_on  := :new.updated_on;
        :new.created_by  := :new.updated_by;
    ELSE
        :new.row_version := NVL(:old.row_version, 0) + 1;
    END IF;

    -- Password hashing logic
    IF :new.password_plain IS NOT NULL THEN
        IF INSERTING
           OR :old.password_plain IS NULL
           OR :new.password_plain <> :old.password_plain
        THEN
            :new.password_salt := DBMS_RANDOM.STRING('x', 20);

            :new.password_hash := apex_util.get_hash(
                                     apex_t_varchar2(:new.password_plain || :new.password_salt),
                                     FALSE
                                  );

            :new.password_plain := NULL;
        END IF;
    END IF;
END;
/
    


-- =========================================================
-- 3. AUTHENTICATION PACKAGE
-- =========================================================

CREATE OR REPLACE PACKAGE crm_auth AS
    FUNCTION authenticate_user (
        p_username IN VARCHAR2,
        p_password IN VARCHAR2
    ) RETURN BOOLEAN;

    PROCEDURE post_auth;
END crm_auth;
/
    

CREATE OR REPLACE PACKAGE BODY crm_auth AS

    FUNCTION authenticate_user (
        p_username IN VARCHAR2,
        p_password IN VARCHAR2
    ) RETURN BOOLEAN
    IS
        l_hash      crm_users.password_hash%TYPE;
        l_salt      crm_users.password_salt%TYPE;
        l_test_hash VARCHAR2(255);
    BEGIN
        SELECT password_hash,
               password_salt
        INTO   l_hash,
               l_salt
        FROM   crm_users
        WHERE  LOWER(username) = LOWER(p_username);

        l_test_hash := apex_util.get_hash(
                          apex_t_varchar2(p_password || l_salt),
                          FALSE
                       );

        IF l_test_hash = l_hash THEN
            apex_util.set_authentication_result(0);
            RETURN TRUE;
        ELSE
            apex_util.set_authentication_result(4);
            RETURN FALSE;
        END IF;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            apex_util.set_authentication_result(1);
            RETURN FALSE;

        WHEN OTHERS THEN
            apex_util.set_authentication_result(7);
            apex_util.set_custom_auth_status(SQLERRM);
            RETURN FALSE;
    END authenticate_user;



    PROCEDURE post_auth IS
        l_role_name crm_roles.role_name%TYPE;
    BEGIN
        SELECT r.role_name
        INTO   l_role_name
        FROM   crm_users u
        JOIN   crm_roles r
               ON r.id = u.role_id
        WHERE  LOWER(u.username) = LOWER(v('APP_USER'));

        apex_authorization.enable_dynamic_groups(
            p_group_names => apex_t_varchar2(l_role_name)
        );

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            NULL;
    END post_auth;

END crm_auth;
/
    


-- =========================================================
-- 4. SAMPLE DATA
-- =========================================================

INSERT INTO crm_roles
    (id, role_name, role_description, row_version,
     created_on, created_by, updated_on, updated_by)
VALUES
    (1, 'Admin', 'System administrator with full access',
     1, SYSDATE - 100, 'SYSTEM', SYSDATE - 100, 'SYSTEM');

INSERT INTO crm_roles VALUES
    (2, 'Sales Manager', 'Manages sales team and accounts',
     1, SYSDATE - 100, 'SYSTEM', SYSDATE - 100, 'SYSTEM');

INSERT INTO crm_roles VALUES
    (3, 'Sales Rep', 'Handles customer accounts and deals',
     1, SYSDATE - 100, 'SYSTEM', SYSDATE - 100, 'SYSTEM');

INSERT INTO crm_roles VALUES
    (4, 'Support Agent', 'Provides customer support',
     1, SYSDATE - 100, 'SYSTEM', SYSDATE - 100, 'SYSTEM');

INSERT INTO crm_roles VALUES
    (5, 'Viewer', 'Read only access to reports',
     1, SYSDATE - 100, 'SYSTEM', SYSDATE - 100, 'SYSTEM');

COMMIT;


-- =========================================================
-- USERS
-- =========================================================

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES (
    'admin', 'admin@acmecrm.com', 'Welcome123!', 'John', 'Admin',
    1, '555-0001', 1,
    SYSDATE, 'SYSTEM', SYSDATE, 'SYSTEM'
);

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES
('smiller','sarah.miller@acmecrm.com','Welcome123!','Sarah','Miller',2,'5550101',1,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM');

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES
('rpatel','raj.patel@acmecrm.com','Welcome123!','Raj','Patel',3,'5550102',1,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM');

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES
('achen','alex.chen@acmecrm.com','Welcome123!','Alex','Chen',3,'5550103',1,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM');

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES
('mroberts','mia.roberts@acmecrm.com','Welcome123!','Mia','Roberts',4,'5550201',1,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM');

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES
('tnguyen','tom.nguyen@acmecrm.com','Welcome123!','Tom','Nguyen',4,'5550202',1,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM');

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES
('dlee','daniel.lee@acmecrm.com','Welcome123!','Daniel','Lee',5,'5550301',1,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM');

INSERT INTO crm_users (
    username, email, password_plain, first_name, last_name,
    role_id, phone, row_version,
    created_on, created_by, updated_on, updated_by
) VALUES
('sgupta','sneha.gupta@acmecrm.com','Welcome123!','Sneha','Gupta',5,'5550302',1,SYSDATE,'SYSTEM',SYSDATE,'SYSTEM');

COMMIT;
