create table tms_audit_log (
  log_id      number generated by default on null as identity primary key,
  table_name  varchar2(128) not null,
  operation   varchar2(10) not null,
  old_values  clob,
  new_values  clob,
  changed_by  varchar2(255) default sys_context('USERENV', 'SESSION_USER') not null,
  changed_at  timestamp with local time zone default systimestamp not null,
  constraint tms_audit_log_op_ck
    check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  constraint tms_audit_log_old_json
    check (old_values is json),
  constraint tms_audit_log_new_json
    check (new_values is json)
);
